namespace Project_Euler;

/// <summary>
/// Solves Project Euler Problem 44: Pentagon numbers.
/// Pentagonal numbers are generated by the formula, Pn=n(3n-1)/2. The first ten pentagonal numbers are:
/// 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
/// It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 - 22 = 48, is not pentagonal.
/// Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk - Pj| is minimised; what is the value of D?
/// </summary>
public class Problem044 : Problem {
    /// <summary>
    /// Solves Project Euler Problem 44.
    /// </summary>
    /// <returns>The minimal difference D.</returns>
    public override object Solve() {
        return MinPentagonDifference();
    }

    private object MinPentagonDifference() {
        // Strategy: Iterate on k to generate P_k.
        // For each P_k, iterate on j < k to generate P_j.
        // We want to minimize D = P_k - P_j.
        // We'll use a dynamic list of pentagonals to avoid recomputing.
        // This standard solution typically finds the minimal D efficiently.

        List<long> pentagonals = new List<long>();
        long i = 1;

        while (true) {
            long pi = i * (3 * i - 1) / 2;
            pentagonals.Add(pi);

            // Check backwards against all previous P_j
            // We want D = pi - pj to be pentagonal AND pi + pj to be pentagonal.
            // If so, D is a candidate.

            for (int j = (int)i - 2; j >= 0; j--) {
                long pj = pentagonals[j];
                long diff = pi - pj;
                long sum = pi + pj;

                if (IsPentagonal(diff) && IsPentagonal(sum)) {
                    return diff;
                }
            }
            i++;
        }
    }

    private bool IsPentagonal(long n) {
        if (n <= 0) return false;
        long val = 1 + 24 * n;
        long sqrt = (long)Math.Sqrt(val);
        return sqrt * sqrt == val && (sqrt + 1) % 6 == 0;
    }
}
